# Gradle JVM settings
org.gradle.jvmargs=-Xmx1536m

# Gradle JDK path (JDK 17)
org.gradle.java.home=C\:\\Users\\mehar\\Java\\jdk-17\\jdk-17.0.11

# Enable parallel build (optional)
# org.gradle.parallel=true
# Suppress compileSdk warnings
android.suppressUnsupportedCompileSdk=35

# AndroidX support (optional)
android.useAndroidX=true
android.enableJetifier=true
